--- #YAML:1.0
name:               Template-HTML
version:            0.04
abstract:           Automatic HTML encoding of tags for Template Toolkit
author:
    - Martyn Smith <msmith@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Template:  1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
