--- #YAML:1.0
name:                Template-HTML
version:             0.01
abstract:            Automatic HTML encoding of tags for Template Toolkit
license:             perl
author:              
    - Martyn Smith <msmith@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Template:                      1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
